### PR TITLE
Fix: Flie.objects.only("id") query when deleting a user.

### PR DESCRIPTION
**Pull request by wiltso**
## Description

When deleting a User object, Django's `django.db.models.deletion.Collector` will make a query like this: File.objects.filter(owner=user).only("id").
This then leads to a recursion error due to that the `filler.models.File` object requires that the following fields are present:
- _file_size
- sha1
- is_public

## Related resources

- https://github.com/django-cms/django-filer/issues/1290

## Checklist

* [x] I have opened this pull request against ``master``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-filer/blob/master/docs/development.rst#contributing) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by vinitkumar** [comment]
@wiltso Do you remember if the error you got is almost like this?

```python
IntegrityError at /admin/customroles/siteuser/
update or delete on table "auth_user" violates foreign key constraint "filer_file_owner_id_b9e32671_fk_auth_user_id" on table "filer_file"
DETAIL: Key (id)=(89) is still referenced from table "filer_file".
```

**Comment by wiltso** [comment]
I was actually getting an recursion error.
You can replicate it by doing `File.objects.filter(owner=u).only("id")`.

**Comment by fsbraun** [comment]
@wiltso Sorry, that this got "lost". I would like to take it up. I'd really appreciate, if we could add a test for it:

* Create user
* Create filer object
* Delete user

Do you think you could add such an test?

**Comment by fsbraun** [comment]
@wiltso I've created a follow-up PR (#1357) that includes the cherry-pick of this PR and a simple test. 
I really would like to get this fix merged now.

**Comment by fsbraun** [comment]
Implemented in #1357

**Pull request closed without merging**
