### PR TITLE
feat: open edit file popup from file widget

### PR DESCRIPTION
**Pull request by fabien-michel**
## Description

Add an edit button to file widget which open the edit file popup.

There is a UI change the `pencil` button now open the edit file popup. The existing lookup button now has a `file` icon.

## Related resources

* https://discourse.django-cms.org/t/allow-to-enter-edit-form-of-django-filers-file-from-widget/238

## Checklist

* [x] I have opened this pull request against ``master``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-filer/blob/master/docs/development.rst#contributing) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by marksweb** [comment]
This sounds really useful. I'll install this & give it a go 👍

**Comment by Will-Hoey** [comment]
@marksweb @fabien-michel Is there any update on this? Found this PR recently and I have a use case for this so would love to get it into a release!

**Comment by fabien-michel** [comment]
Ping !

**Comment by benzkji** [comment]
a pity that such useful things just get lost

**Comment by fabien-michel** [comment]
The PR is now in sync with master and with small fix for latest djangocms

**Comment by fsbraun** [comment]
I put it on our sprint list for tomorrow and Friday.

**Comment by fsbraun** [comment]
@fabien-michel  Can you also quickly look at the small flake8 issues? Thanks!

**Comment by fsbraun** [comment]
Hm. Does not seem to work for me:

1. I get CSS problems with an empty field (see image below)
2. I lose the option to choose a new file (see 2nd image)

Am I doing something wrong?

image

image
(the missing thumbnail problem is not due to the pull request but due to my setup.)

**Comment by fabien-michel** [comment]
I need help to make the `static/filer/js/addons/filer_popup_response` file pass linting. I've tried many things without success.
This file mimic what is done in the file https://github.com/django/django/blob/main/django/contrib/admin/static/admin/js/popup_response.js from django code.
The linter doesn't pass using the `const` keyword, but using `var` force it to be at top. Doing that make `tests:unit` task to fail probably because detected as "null"

**Review by fsbraun — COMMENTED** [review]
Hi @fabien-michel ! A very use PR! Thank you so much!

I've added two comments:

* When no file is selected the button "Chose file" shows an icon with an image. For consistency, would that be the icon to show on the button to replace the file?
* I still have the styling problem. Maybe the space for the icons is too smal?
* As an additional thought: I never got the idea of opening the image or file by clicking on the icon. Maybe it is worth considering that clicking the icon should also trigger the "replace-file" popup? What's your opinion on that.

Finally, do not worry about the js linting. I've got a PR coming up that updates the gulp build process to node 16. I will resolve this issue then.

**Comment by fsbraun** [comment]
Since the test coverage is rather mediocre in this repo, adding a test that checks if the file widget provides the right URL would also be a great.

**Comment by benzkji** [comment]
I would propose a magnifier icon for searching/replacing a file, and the pencil to open the file's change view in the popup.

**Review by fsbraun — APPROVED** [review]

**Comment by fsbraun** [comment]
One last thing: The margins between the buttons on the right differ: (15px and 10px). Maybe both 10px?

image

**Comment by fabien-michel** [comment]
> One last thing: The margins between the buttons on the right differ: (15px and 10px). Maybe both 10px?

🤔 I thought I had fixed this

**Comment by fabien-michel** [comment]
> One last thing: The margins between the buttons on the right differ: (15px and 10px). Maybe both 10px?

I'm can't reproduce. Can you double-check ? May be its a cache issue ?

**Comment by fsbraun** [comment]
Can't be the cache: The magnifying glass shows up. Have you included the compiled css?

**Comment by fabien-michel** [comment]
I can't find where the 15px margin-left you see on .related-lookup is  coming from. 
Native django is to 5px (https://github.com/django/django/blame/549d6ffeb6d626b023acc40c3bb2093b4b25b3d6/django/contrib/admin/static/admin/css/forms.css#LL509C22-L509C22)
djangocms_admin_style is to https://github.com/django-cms/djangocms-admin-style/blob/b38d2b0b3a9db80112c7fc63f313fa671fdd0ad0/djangocms_admin_style/sass/components/_forms.scss#L88

Any idea ?

**Comment by fsbraun** [comment]
Here's Safari's trace:
image

Clearly, it comes from Django. Maybe your form is set up differently. It's dependent on the fieldset's `aligned` class. I'd suggest fixing both margins to 10px for filer (and overwriting Django's style). This way it'll be consistent.

**Comment by fabien-michel** [comment]
👌 Thanks for your time on this PR

**Pull request merged**
