### PR TITLE
import_files refactoring

### PR DESCRIPTION
**Pull request by skirsdeda**
This includes a rewrite of import_files which now has these features:
- Import from any Django storage
- Use standard File class detection (matches_file_type)
- Make import_files repeatable by adding duplicate file detection and user action selection. Now it is possible to import the same path to the same filer target folder by selecting --duplicate-action=update and only changed files will be overwriten, no duplicates will be created.

The big thing is size/image size/sha calculation optimization which turned out to be somewhat complicated. Now these file attributes are only recalculated from storage when file's url changes (the only proper way to detect if file contents were changed that I found). This could be improved though:
- File.sha1 could be renamed to _sha1, then get_sha() could be renamed to sha1 and become a property (just like size and image_size)
- get_file_id() could be improved and if we had a model field for this, database hit in data_changed() could be removed and FileQuerySet.iterator override wouldn't be necessary

### CODE REVIEW

**Comment by skirsdeda** [comment]
So apparently **FolderAdmin.resize_images** stopped working, because it sets **image.file.file** directly and file name doesn't change after that. Since it is very difficult to tell apart **file.file** set through **\__init\__** from file.file set by other code (which actually changes content), I would suggest rewriting **resize_images** so that file name changes after resize.

**Comment by yakky** [comment]
@skirsdeda could you check the failure in travis?

**Comment by skirsdeda** [comment]
My comment above (https://github.com/stefanfoulis/django-filer/pull/500#issuecomment-75755696) is about failure in travis. Is the proposed solution good?

**Comment by yakky** [comment]
@skirsdeda sorry for not getting back sooner.
Go ahead with the proposed change

**Comment by stefanfoulis** [comment]
@skirsdeda sorry for not merging this sooner. If you rebase we can merge this.

**Comment by skirsdeda** [comment]
@stefanfoulis Good to hear. I'll get back to this then. I think size/image size/sha calculation part still needs some work.

**Comment by mkoistinen** [comment]
@skirsdeda What's the status on this? We're preparing a release for soonish, will we be able to merge this into it?

**Comment by skirsdeda** [comment]
@mkoistinen What is the timeframe (roughly) for 1.3.0?

**Comment by skirsdeda** [comment]
I'll remove size/sha1 recalculation stuff from this PR and leave only import_files refactoring some time soonish.

**Comment by jccode** [comment]
What's the status on this? Why not merge this PR? I am facing this issue as well, `import_files` command is not compatible with Django 1.10 , please refer to the issue #966 . Thanks

**Comment by skirsdeda** [comment]
@jccode this has been finished more than 2 years ago :) But nobody cares to merge it.

**Comment by jdcookie** [comment]
So this still seems to be an issue. Trying to use Django 1.11 and can't because of this issue in the import_files command. Is it possible to revisit this?

**Comment by yakky** [comment]
@skirsdeda now that we are working towards 1.4, any chance you can rebase this on top of current develop?
Some cleanup has already been addressed in #1058, you can thus concentrate on the actual features

**Pull request closed without merging**
