### PR TITLE
fix: django-storage 1.14 complains about files being opened twice when copying

### PR DESCRIPTION
**Pull request by fsbraun**
## Description

While the root cause of the bug #1417 might be in django-storages 1.14, this quick-fix ensures that any ValueError raised opening a file for copying does not crash the file application with a server error.

## Related resources

* #1417 
* #...

## Checklist

* [x] I have opened this pull request against ``master``
* [x] I have added or modified the tests when changing logic
* [x] I have followed [the conventional commits guidelines](https://www.conventionalcommits.org/) to add meaningful information into the changelog
* [x] I have read the [contribution guidelines ](https://github.com/django-cms/django-filer/blob/master/docs/development.rst#contributing) and I have joined #workgroup-pr-review on 
[Slack](https://www.django-cms.org/slack) to find a “pr review buddy” who is going to review my pull request.

### CODE REVIEW

**Comment by vinitkumar** [comment]
@fsbraun Is it possible to have a test with this patch?

**Comment by fsbraun** [comment]
@vinitkumar I know! I've been thinking about it, but I do not see a way of testing this without the specific implementation of `django-storage`'s S3Storage on an AWS instance. I frankly believe that the underlying issue is between Django and django-storage, but it's hard to tell. Since the`try` `except` block. 

Any idea how to test this?

**Comment by vinitkumar** [comment]
@fsbraun I don't know. Seems hard to implement in the test. Have you tried testing this patch with a real s3 backend?

**Comment by fsbraun** [comment]
@vinitkumar I tested it on my staging setup with AWS: Without the fix, copying files fails and a copy of the first file remains in the source folder. After fixing it, copying works fine.

The fix also does not affect local file storage (which just runs `seek(0)` in case of a reopen).

**Review by vinitkumar — APPROVED** [review]
Looks good to me. Let's get this merged and released 🚢  🚀

**Pull request merged**
