### PR TITLE
Easier File and Image model fields usage

### PR DESCRIPTION
**Pull request by DylannCordel**
With this pull request, when a dev define an Image's foeignKey, he can configure :
- available mimetypes via the FileMimetypeValidator : takes a list of allowed mime subtypes (e.g: `image/jpeg`) and/or mimetypes (e.g: `image/*`)
- choose which upload method is available when the widget will be displayed (by default : old method is activated (file lookup). the second one is "direct upload" : a simple "browse" button : when we choose a file, ajax upload is performed. Both methods can be enabled together : choose a file from the website ou on the PC)
- default folder where the file will be uploaded : when direct upload is enabled and the user upload a file, the new file will be linked to the configured folder. It's done by sending a folder "key" which must be a class method of a `DefaultFolderGetter child`. This method takes the request and must return a folder.

Tests for "dynamic" folder destination and mimetype detections  have been added.
If you think this pull request is usefull and mergeable, I'll add:
- documentation 
- tests for third party models with File/Image foreign keys.
- direct_upload will also send a "related_field" data of this format : "model_name.field_name" (e.g: `'News.illustration'`). `direct_upload`'s view will be able to retrieve validators associated to this field and reject files during the ajax upload and not only when the object (the news) is saved.

Simple usage exemple:

``` python
#my_news_app/models.py
# [...] imports and other required things...

class News(NewsboxBase):
    illustration = FilerImageField(
        verbose_name=_('illustration'), 
        default_direct_upload_enabled=True, 
        #add a "browse" button with ajax upload
        default_file_lookup_enabled=False, 
        #remove the file lookup link. The user will only have a browse button to add new files
        direct_upload_folder_key='USER_OWN_FOLDER', 
        #file will be uploaded in a specifc folder owned by the authenticated user
        validators=[FileMimetypeValidator(['image/png', 'image/jpeg'])], 
        #only jpeg and PNG are allowed
        null=True, blank=True)
```

``` python
#my_news_app/utils.py
from filer.utils.folders import DefaultFolderGetter

class MyCustomFolderGetter(DefaultFolderGetter)
    @classmethod
    def USER_OWN_FOLDER(cls, request):
        if not request.user.is_authenticated():
            return None
        folder = Folder.objects.filter(owner=request.user, parent_id=USERS_FOLDER_PK)[0:1]
        if not folder:
            folder = Folder()
            folder.name = request.user.username
            folder.parent_id = USERS_FOLDER_PK
            folder.owner = request.user
            folder.save()
        else:
            folder = folder[0]
        return folder
```

``` python
#project/settings.py

FILER_DEFAULT_FOLDER_GETTER = 'my_news_app.utils.MyCustomFolderGetter'
```

### CODE REVIEW

**Comment by yakky** [comment]
@DylannCordel this is awesome!
Please go ahead

**Comment by DylannCordel** [comment]
I rebased with the "develop" branch ( @yakky : sorry for noise : I did a pull instead of a rebase and I pushed a real mess... Thx to @ollb for his help about git to clean it)

I added:

* documentation
* tests for third party models with File/Image foreign keys. As I test HTML content to check if file_lookup and/or file_choose buttons are available, I added `lxml` to dependencies of tests.
* direct_upload will also send a "related_field" data of this format : `app_label.model_name.field_name`
  (e.g: `myapp.News.illustration`). direct_upload's view will be able to retrieve validators associated 
  to this field and reject files during the ajax upload and not only when the object (the news) 
  is saved.

I'd like to add tests for Reversed ForeignKey relations (`thirdparty_app` has already a `ExampleGalleryElement` with a FK related to `gallery_elements` on `Example` model), but this is not only for this PR : those tests should exist. In fact, I would like to add tests with Selenium because `django-file` have a great part of his features which need javascript and are currently not tested. I'll open an issue for this precisely.

**Comment by DylannCordel** [comment]
rebase with develop

**Comment by mkoistinen** [comment]
@DylannCordel I really like this PR. It looks like we've been making it hard for you to keep up. Sorry about that. Can you rebase one more time and I'll try to get this into a release soon.

**Comment by DylannCordel** [comment]
@mkoistinen okay, I'll do this ASAP.

**Comment by DylannCordel** [comment]
Code is rebased. I had to throw in trash some part of my work because of the dropzone addition which duplicates a part of the features of this PR (which will be 1 year old soon).

**Comment by mkoistinen** [comment]
@DylannCordel we're preparing a release 1.3 now, any chance you could (yet again, sorry!) rebase?

**Comment by qodrinzo** [comment]
+1 for this

**Pull request closed without merging**
