### PR TITLE
Docs: add topic about populating models programmatically

### PR DESCRIPTION
**Pull request by scardine**
Add topic about how to populate a `FilerFileField` field programmatically if all you have is the filesystem path to some random file.

### CODE REVIEW

**Comment by czpython** [comment]
@scardine 
Thanks for the contribution.

@evildmp Please have look

**Comment by vstoykov** [comment]
Actually the owner is not required. But there is a problem with optional owner is that in the filer nobody will see it because the file is not in any folder and files which are not in folder are shown only to owners of the file. Probably will be good to mention how to create a folder in filer and to create the File object as member of the folder. In this situation if people want to programatically create files they can choose in which filer folder to be placed.

About creating folders I actually think that programatic API need to be created for easily creating nested folders (like `mkdir -p path/to/folder`) which will create all needed folder objects in filer if they don't exists and then returns the list child. This is not related to proposed documentation directly but can help in ways where people want to programatically create files in filer in desired locations.

**Comment by elioscordo** [comment]
Hello,
the docs cover only images.
```
file_obj = DjangoFile(
                    open(path),
                    name=name
                )
                file = File(
                    original_filename = filename,
                    file = file_obj
                )
                file.save()
```
it fails because of the thumbnails:

```
 File "/Users/elio/projects/is/git/server/venv/lib/python3.9/site-packages/django/db/models/fields/files.py", line 307, in pre_save
    file.save(file.name, file.file, save=False)
  File "/Users/elio/projects/is/git/server/venv/lib/python3.9/site-packages/filer/fields/multistorage_file.py", line 120, in save
    super().save(name, content, save)
  File "/Users/elio/projects/is/git/server/venv/lib/python3.9/site-packages/easy_thumbnails/files.py", line 669, in save
    super().save(name, content, *args, **kwargs)
  File "/Users/elio/projects/is/git/server/venv/lib/python3.9/site-packages/django/db/models/fields/files.py", line 87, in save
    self.name = self.storage.save(name, content, max_length=self.field.max_length)
  File "/Users/elio/projects/is/git/server/venv/lib/python3.9/site-packages/django/core/files/storage.py", line 52, in save
    return self._save(name, content)
  File "/Users/elio/projects/is/git/server/venv/lib/python3.9/site-packages/django/core/files/storage.py", line 271, in _save
    for chunk in content.chunks():
  File "/Users/elio/projects/is/git/server/venv/lib/python3.9/site-packages/django/core/files/base.py", line 60, in chunks
    data = self.read(chunk_size)
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

any help to create programatically generic files, please?

**Comment by majdal** [comment]
For those encountering the same issue, you probably are trying to open a binary file. line 110 should have `open(path, 'rb')`. See [this](https://stackoverflow.com/questions/42339876/error-unicodedecodeerror-utf-8-codec-cant-decode-byte-0xff-in-position-0-in) for more details.

**Pull request closed without merging**
