### PR TITLE
Change mptt version dependency to be PEP440 compatible

### PR DESCRIPTION
**Pull request by yakky**

### CODE REVIEW

**Comment by gavinwahl** [comment]
Is this going to be released soon?

**Comment by pipermerriam** [comment]
> Is this going to be released soon?
 :+1:

**Comment by pipermerriam** [comment]
Any word on a 0.9.9 release with this change in it?

**Comment by yakky** [comment]
0.9.9 has been released!

**Comment by pipermerriam** [comment]
Thanks so much @yakky

**Comment by BertrandBordage** [comment]
@yakky Could you add 0.9.9 to PyPI please? Thanks :)

**Comment by yakky** [comment]
@BertrandBordage sorry: the upload returned an error but I haven't found out until this morning. Will push it soon

**Comment by yakky** [comment]
@BertrandBordage @pipermerriam now released for real!

**Comment by BertrandBordage** [comment]
Thank you @yakky :D

**Pull request merged**
